move the workflow ymal file in workflows folder

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,7 +12,7 @@ jobs:
     steps:
       - name: Failed steps
         run: |
-        echo "I will fail"
-        exit 1 
+          echo "I will fail"
+          exit 1 
       - name: Say goodbye
         run: echo "GoodBye"
